//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP2_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Information()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Sales = new HashSet<Sale>();
            this.Users = new HashSet<User>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "Full Name is required")]
        [Display(Name = "Full_Name:")]
        public string Full_Name { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [Display(Name = "Email Address:")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Phone number is required")]
        [Display(Name = "Phone:")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Account number is required")]
        [Display(Name = "Acc_Number:")]
        public string Acc_Number { get; set; }

        [Required(ErrorMessage = "Balance is required")]
        [Display(Name = "Balance:")]
        public double Balance { get; set; }

        [Required(ErrorMessage = "Work position is required")]
        [Display(Name = "Work_Position:")]
        public string Work_Position { get; set; }

        [Required(ErrorMessage = "User Type is required")]
        [Display(Name = "usertype:")]
        public string usertype { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
