//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP2_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Sales =     new HashSet<Sale>();
            this.Stocks =    new HashSet<Stock>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Product Name is required")]
        [Display(Name = "Product Name:")]
        public string name { get; set; }
        [Required(ErrorMessage = "Catagory is required")]
        [Display(Name = "Category Name:")]
        public int category_id { get; set; }
        [Required(ErrorMessage = "Price is required")]
        [Display(Name = "Price:")]
        [Range(0, 10000000, ErrorMessage = "Out of range")]
        public double price { get; set; }
        [Required(ErrorMessage = "Quantity is required")]
        [Range(0, 10000000, ErrorMessage = "Out of range")]
        [Display(Name = "Quantity:")]
        public int quantity { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
