//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP2_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
public int id { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [Display(Name = "password:")]
        public string password { get; set; }

 

        [Required(ErrorMessage = "Type is required")]
        [Display(Name = "Type:")]
        public string type { get; set; }

 

        [Required(ErrorMessage = "Type is required")]
        [Display(Name = "permission:")]
        public string permission { get; set; }

 

        [Required(ErrorMessage = "Type is required")]
        [Display(Name = "info_id:")]
        public int info_id { get; set; }

 

        [Required(ErrorMessage = "User Name is required")]
        [Display(Name = "Username:")]
        public string username { get; set; }
        public virtual Information Information { get; set; }
    }
}
